export const fileToolPromptLines = [
  '当用户需要知道某个目录下有哪些文件、先定位项目结构或先找文件时，先调用 listFiles。',
  '当用户需要按关键词搜索、查找、定位某个变量、函数、配置或文案出现在哪里时，必须调用 searchInFiles。',
  '当用户要求查看、总结、解释当前工作区中的代码、配置或文档时，调用 readLocalFile 读取真实文件内容，不要臆测。',
  '当用户明确要求同时查看、比较、汇总多个文件时，优先调用 readMultipleFiles。',
  '当用户要求创建新文件或在已知完整内容时重写文件，使用 writeFile。',
  '当用户要求对现有文件做小范围精确修改时，优先先读取文件，再使用 replaceInFile。',
  '当用户要求删除文件时，使用 deleteFile。',
  '当用户要求移动或重命名文件时，使用 moveFile。',
  '当用户要求对单个文件一次做多处精确修改时，优先使用 applyFileEdits。',
  '当用户要求查看有哪些可回滚的历史备份时，使用 listBackups。',
  '当用户要求撤销上一步、回滚最近一次修改时，优先使用 rollbackLatest。',
  '当用户没有明确给出 backupId，但需要先查看或确认最近一条备份时，可以调用 getLatestBackup。',
  '当用户明确给出 backupId 或你已经拿到目标 backupId 时，使用 restoreBackup 执行恢复。',
  '在修改文件之前，优先先读取相关文件内容，避免盲改。',
  '写类工具会自动返回 backup 信息。文件修改完成后，要基于工具返回的 validation 字段确认结果是否符合预期；validation 里的 Git 状态和 diff 也属于自检依据。',
]
